environment:
  nodejs_version: "4.0"

install:
  - ps: Install-Product node $env:nodejs_version
  - ps: choco install make
  - ps: choco install chromium
  - ps: choco install googlechrome
  - npm install --no-optional

test_script:
  - set PATH=.\node_modules\.bin;%PATH%
  - node --version
  - npm --version
  - make test

build: off